name: BetterHelp
author: ondraczsk
api: [1.14.0, 2.0.0]
version: 1.0
main: BetterHelp/Main.php 

# Commands:
command:
	help:
		description: Napoveda
		usage: /help

# Permissions 
permissions:
	help.command:
		default: true
