name: BetterHelp
author: ondraczsk
api: [1.14.0, 2.0.0]
version: 1.0
main: BetterHelp/Main

commands:
 help:
  permission: help.cmd
  description: Napoveda
  usage: /help

permissions:
 help.cmd:
  default: true
  description: ZMusicBox Commands
